version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
  web:
    build: .
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver"
    volumes:
      - .:/random_api_json
    expose:
      - 8000
    depends_on:
      - db
    environment:
      - DB_NAME=
      - DB_USER=
      - USER_PASSWORD=
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=
      - DEBUG_VALUE=
      - DJANGO_DEV=
